Add setting to enable unlisted emotes
SevenTV/chatterino7 pull request #67
Opened 2022-01-10 00:49 UTC by goldbattle

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This add support for hiding unlisted emotes and a setting to enable them if the user wishes to do so. This was requested as per https://github.com/Chatterino/chatterino2/pull/3071#issuecomment-1008454760 and is part of my effort to upstream 7tv support (see https://github.com/Chatterino/chatterino2/pull/3071#issuecomment-1008367948).

2022-01-10 01:43 UTC, MrAuro commented
While testing this I noticed that you have to reload all emotes (F5) anytime you update the newly added setting for the changes to take effect

![image](https://user-images.githubusercontent.com/35087590/148709709-062b8faa-e8a8-4658-86df-2b587ecd1d68.png)

2022-01-10 02:27 UTC, goldbattle commented
Good point, I guess that is something people would want. I simply call refresh on the 7TV emotes if the setting is changed.

2022-01-10 08:02 UTC, jammehcow commented
I'm not the biggest fan of refreshing all emotes each time the setting is changed. Would prefer that it was handled locally, but since this setting isn't going to be changed frequently it's probably fine.

![pajaBing 1x](https://user-images.githubusercontent.com/4962764/148734043-08ab9eb1-38be-4d7c-bd79-0c3759671587.gif) @zneix would like your opinion.

2022-03-19 21:54 UTC, goldbattle commented
Are you able to take a look at this @zneix?

2022-03-25 02:54 UTC, TroyKomodo approved these changes

2022-03-25 03:04 UTC, TroyKomodo commented
@goldbattle there seems to be some mistakes, please verify that this compiles and i will be happy to merge it.

2022-03-25 03:05 UTC, TroyKomodo requested changes

2022-03-25 03:05 UTC, TroyKomodo commented on src/widgets/settingspages/GeneralPage.cpp
> +            getApp()->twitch.server->forEachChannelAndSpecialChannels(
```suggestion
            getApp()->twitch->server->forEachChannelAndSpecialChannels(
```

2022-03-25 03:06 UTC, Felanbird commented on src/widgets/settingspages/GeneralPage.cpp
> +            getApp()->twitch.server->forEachChannelAndSpecialChannels(
```suggestion
            getApp()->twitch->server->forEachChannelAndSpecialChannels(
```

2022-03-25 03:07 UTC, Felanbird commented on src/widgets/settingspages/GeneralPage.cpp
> +            getApp()->twitch.server->forEachChannelAndSpecialChannels(
hey i was gonna do that

2022-03-25 03:09 UTC, goldbattle commented
I can check this weekend, but feel free to fix and merge if it works for
you.

On Thu, Mar 24, 2022, 11:07 PM Felanbird ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/widgets/settingspages/GeneralPage.cpp
> <https://github.com/SevenTV/chatterino7/pull/67#discussion_r834919102>:
>
> > @@ -315,6 +317,23 @@ void GeneralPage::initLayout(GeneralPageView &layout)
>
>      layout.addCheckbox("Remove spaces between emotes",
>                         s.removeSpacesBetweenEmotes);
> +    layout.addCheckbox("Show unlisted / unapproved emotes (7TV only)",
> +                       s.showUnlistedEmotes);
> +    s.showUnlistedEmotes.connect(
> +        []() {
> +            getApp()->twitch.server->forEachChannelAndSpecialChannels(
>
> hey i was gonna do that
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SevenTV/chatterino7/pull/67#discussion_r834919102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAQ6TYVZHFJRW2FIJKVD3ZDVBUUWBANCNFSM5LSPYTTA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-25 03:25 UTC, TroyKomodo commented on src/widgets/settingspages/GeneralPage.cpp
> +            getApp()->twitch.server->forEachChannelAndSpecialChannels(
it was wrong.

2022-03-25 03:25 UTC, TroyKomodo commented on src/widgets/settingspages/GeneralPage.cpp
> +            getApp()->twitch.server->forEachChannelAndSpecialChannels(
💀

2022-03-25 03:26 UTC, TroyKomodo commented on src/widgets/settingspages/GeneralPage.cpp
> +            getApp()->twitch->server->forEachChannelAndSpecialChannels(
```suggestion
            getApp()->twitch->forEachChannelAndSpecialChannels(
```

2022-03-25 03:26 UTC, Felanbird commented on src/widgets/settingspages/GeneralPage.cpp
> +            getApp()->twitch.server->forEachChannelAndSpecialChannels(
ya we suck

2022-03-25 04:10 UTC, TroyKomodo approved these changes

2022-03-25 04:33 UTC, merged

2022-03-25 04:38 UTC, TroyKomodo commented
@goldbattle Feel free to tag me on discord if you do not have the contributor role.